main: io.github.km127pl.itemsplus.Main
name: ItemsPlus
author: KM127PL
version: 1.0

commands:
  i:
    description: Test give command.
    usage: /<command>
  itemsplus:
    description: ItemsPlus main command.
    usage: /<command> [reload, restart]
    aliases: ["ip"]